### PR TITLE
fix(messageinput, commenteditable): change the onKeyDown event to onKeyPress event for fixing onKeyDown event fires twice when typing in Korean and then typing enter

### LINKED ISSUE #9: OnKeyDown event occurs twice when typing in Korean and then hitting enter
Hi, thank you for intuitive and awesome chat-ui library.

I'm using it well, but there are some bugs like following situations.

OnKeyDown event occurs twice when typing in Korean and then hitting enter. So Last Korean Character printed one more time.
Korean Input Bug

### PR DESCRIPTION
**Pull request by HwangTaehyun**
I changed the onKeyDown event to onKeyPress event for fixing onKeyDown event fires twice when typing in Korean and then typing enter. Then it works charm.
Thank you!
It resolves #9

### CODE REVIEW

**Review by supersnager — CHANGES_REQUESTED** [review]
@HwangTaehyun Please shorten your commit message to meet the commitlint requirements. The current error reported by the commitlint is: 
"header must not be longer than 100 characters, current length is 165 [header-max-length]"

**Comment by HwangTaehyun** [comment]
Oh, I didn't know that commitlint in this project. I'm done fixing the commit message was shortened to be shorter than 100 characters. How did my commit commitlint?

**Comment by supersnager** [comment]
> Oh, I didn't know that commitlint in this project. I'm done fixing the commit message was shortened to be shorter than 100 characters. How did my commit pass commitlint?

I don't know. I will do a fresh clone and check. The most important is that it can be merged now :)

**Pull request merged**
